### ISSUE TITLE
font_awesome_flutter ^7.1.0 is forbidden

### ISSUE THREAD

**Issue by jayjtao** [deven98/YouTubeFlutter#1]
Running "get dependency" will run into -
"The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
Because font_awesome_flutter 7.1.0 requires SDK version <2.0.0 and no versions of font_awesome_flutter match >7.1.0 <8.0.0, font_awesome_flutter ^7.1.0 is forbidden.
So, because youtube_flutter depends on font_awesome_flutter ^7.1.0, version solving failed.
pub get failed (1)"
Since I'm not familiar with font_awesome_flutter", please advise how to resolve this.
Thanks,
Jay

**Comment by d3xvn** [comment]
The dependency version was a bit old. Just upgraded. You can pull changes now and it will run just fine. In case it doesn't, feel free to reopen.
